/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dynamic.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the City service. Represents a row in the &quot;z_City&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.dynamic.model.impl.CityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.dynamic.model.impl.CityImpl}.
 * </p>
 *
 * @author Abhishek
 * @see City
 * @see com.dynamic.model.impl.CityImpl
 * @see com.dynamic.model.impl.CityModelImpl
 * @generated
 */
public interface CityModel extends BaseModel<City> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a city model instance should use the {@link City} interface instead.
	 */

	/**
	 * Returns the primary key of this city.
	 *
	 * @return the primary key of this city
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this city.
	 *
	 * @param primaryKey the primary key of this city
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the state ID of this city.
	 *
	 * @return the state ID of this city
	 */
	public long getStateId();

	/**
	 * Sets the state ID of this city.
	 *
	 * @param stateId the state ID of this city
	 */
	public void setStateId(long stateId);

	/**
	 * Returns the city ID of this city.
	 *
	 * @return the city ID of this city
	 */
	public long getCityId();

	/**
	 * Sets the city ID of this city.
	 *
	 * @param cityId the city ID of this city
	 */
	public void setCityId(long cityId);

	/**
	 * Returns the city name of this city.
	 *
	 * @return the city name of this city
	 */
	@AutoEscape
	public String getCityName();

	/**
	 * Sets the city name of this city.
	 *
	 * @param cityName the city name of this city
	 */
	public void setCityName(String cityName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.dynamic.model.City city);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.dynamic.model.City> toCacheModel();

	@Override
	public com.dynamic.model.City toEscapedModel();

	@Override
	public com.dynamic.model.City toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}